import "./globals.css";
import "./background.css";

export const metadata = {
  title: "Protestáns Vallás Olimpiász",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hu">
      <body className="background rubik">{children}</body>
    </html>
  );
}
